version: 0.2
phases:
  build:
    commands:
      - cd p3LF1
      - zip -r ../p3LF1.zip *
      - cd ../p3LF2
      - zip -r ../p3LF2.zip *
      - cd ..
      - zip -r layer.zip python/
      - aws lambda update-function-code --function-name hw3lf1 --zip-file fileb://p3LF1.zip
      - aws lambda update-function-code --function-name hw3lf2 --zip-file fileb://p3LF2.zip
      - aws lambda publish-layer-version --layer-name mylayer --description "My Python layer" --compatible-runtimes python3.6 python3.7 --zip-file fileb://layer.zip
artifacts:
  type: zip
  # files:
  #   - template.json
  #   - outputtemplate.yml