version: 0.2
phases:
  build:
    commands:
      - cd p3LF1
      - zip -r ../p3LF1.zip *
      - cd ../p3LF2
      - zip -r ../p3LF2.zip *
      - cd ..
      - aws lambda update-function-code --function-name  p3LF1_release --zip-file fileb://p3LF1.zip
      - aws lambda update-function-code --function-name  p3LF2_release --zip-file fileb://p3LF2.zip
      # - aws cloudformation package --template-file template.yml --s3-bucket p3code --output-template-file outputtemplate.yml
artifacts:
  type: zip
  # files:
  #   - template.json
  #   - outputtemplate.yml