AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Resources:
  p3LF1:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./p3LF1
      FunctionName: p3LF1_release
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
    DeletionPolicy: Retain
  p3LF2:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./p3LF2
      FunctionName: p3LF2_release
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
    DeletionPolicy: Retain