AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Resources:
  p3LF1:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      Role: arn:aws:iam::591736655990:role/service-role/p3LF1-role-nvlilped
      CodeUri: ./p3LF1
  p3LF2:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      Role: arn:aws:iam::591736655990:role/service-role/p3LF2-role-3tucnatg
      CodeUri: ./p3LF2