AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Resources:
  p3LF1:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./p3LF1
      FunctionName: p3LF1_release
      # FunctionName: st8lf1
      Handler: lambda_function.lambda_handler
      Role: arn:aws:iam::591736655990:role/PipelineStack-p3LF1Role-1XNL4T65GFSFA
      Runtime: python3.7
      VpcConfig:
        SecurityGroupIds:
          - sg-0aa09fab9bfb48682
        SubnetIds:
          - subnet-0ebcb89d15b80c905
    DeletionPolicy: Retain
  p3LF2:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./p3LF2
      FunctionName: p3LF2_release
      # FunctionName: st8lf2
      Role: 
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      VpcConfig:
        SecurityGroupIds:
          - sg-0aa09fab9bfb48682
        SubnetIds:
          - subnet-0ebcb89d15b80c905
    DeletionPolicy: Retain