AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Resources:
  p3LF1:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./p3LF1
      FunctionName: st8lf1
      Handler: lambda_function.lambda_handler
      Role: 'arn:aws:iam::591736655990:role/service-role/p3LF1-role-nvlilped'
      Runtime: python3.7
    DeletionPolicy: Retain
  p3LF2:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./p3LF2
      FunctionName: st8lf2
      Handler: lambda_function.lambda_handler
      Role: 'arn:aws:iam::591736655990:role/service-role/p3LF2-role-3tucnatg'
      Runtime: python3.7
    DeletionPolicy: Retain